# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies (Django)
  - package-ecosystem: "pip"
    directory: "/backend/attendance_backend"   # adjust if requirements.txt is deeper
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  # Rust dependencies (campus_vision_engine)
  - package-ecosystem: "cargo"
    directory: "/backend/attendance_backend/campus_vision_engine/vision_engine"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  # JS dependencies (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  # JS dependencies (mobile)
  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
