# Generated by Django 5.2.6 on 2025-09-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_qrsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
