# Generated by Django 5.2.6 on 2025-09-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_qrsession_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrsession',
            name='scanned_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrsession',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
