# Generated by Django 5.2.6 on 2025-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_camera_floor_camera_room_cameramatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
    ]
