# Generated by Django 5.2.6 on 2025-12-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_camera_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studenttimetable',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='studenttimetable',
            name='section',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='section',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teachertimetable',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='teachertimetable',
            name='section',
        ),
        migrations.AddField(
            model_name='teacher',
            name='can_teach_classes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacher',
            name='embedding_vector',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacher',
            name='reliability_score',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacher',
            name='workload_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenttimetable',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.schoolclass'),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.schoolclass'),
        ),
    ]
