# Generated by Django 5.2.6 on 2025-12-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_adminaccesskey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAccessKey',
        ),
    ]
