# Generated by Django 5.2.6 on 2025-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='attendance_radius',
            field=models.PositiveIntegerField(default=75, help_text='Radius in meters for attendance'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('organization', 'name')},
        ),
    ]
