# Generated by Django 5.2.6 on 2025-12-28 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_teacher_created_at_teacher_email_teacher_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.organization'),
            preserve_default=False,
        ),
    ]
