# Generated by Django 5.2.6 on 2026-01-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_teacher_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('person_id', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(help_text='Stored in object storage (S3 / MinIO / local dev)', upload_to='faces/%Y/%m/%d/')),
                ('embedding_id', models.BigIntegerField(help_text='Vector ID returned by Rust HNSW index', unique=True)),
                ('embedding_version', models.CharField(default='v1', help_text='Model / embedding version used', max_length=20)),
                ('source', models.CharField(choices=[('enroll', 'Enrollment'), ('cctv', 'CCTV'), ('manual', 'Manual Upload')], default='enroll', max_length=20)),
                ('immutable', models.BooleanField(default=True, help_text='If true, image should not be deleted or replaced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['person_type', 'person_id'], name='attendance__person__5f811f_idx'), models.Index(fields=['created_at'], name='attendance__created_7a3e9f_idx')],
            },
        ),
    ]
