# Generated by Django 5.2.6 on 2026-01-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_faceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='embedding_vector',
        ),
    ]
