# Generated by Django 5.2.6 on 2026-01-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_remove_teacher_embedding_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRejectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('person_id', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_id', models.CharField(max_length=50)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
