# Generated by Django 5.2.6 on 2026-01-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_facerejectionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerejectionlog',
            name='admin_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
