# Generated by Django 5.2.6 on 2026-02-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_facerejectionlog_admin_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='faceimage',
            name='attendance__person__5f811f_idx',
        ),
        migrations.AddField(
            model_name='cameramatch',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.branch'),
        ),
        migrations.AddField(
            model_name='faceimage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.branch'),
        ),
        migrations.AddField(
            model_name='facerejectionlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('branch', 'student', 'teacher', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='faceimage',
            unique_together={('branch', 'person_type', 'person_id', 'embedding_id')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('branch', 'roll_no')},
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('branch', 'employee_id')},
        ),
        migrations.AddIndex(
            model_name='faceimage',
            index=models.Index(fields=['branch', 'person_type', 'person_id'], name='attendance__branch__266077_idx'),
        ),
    ]
