# Generated by Django 5.2.6 on 2026-02-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_remove_faceimage_attendance__person__5f811f_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('branch', 'class_name', 'section')},
        ),
    ]
