# Generated by Django 5.2.6 on 2026-02-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_alter_schoolclass_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrsession',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.branch'),
        ),
    ]
