# Generated by Django 5.2.6 on 2026-02-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_qrsession_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student_timetable',
        ),
        migrations.RemoveField(
            model_name='teachertimetable',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='teachertimetable',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='teachertimetable',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher_timetable',
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.branch')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.schoolclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.timetable'),
        ),
        migrations.DeleteModel(
            name='StudentTimeTable',
        ),
        migrations.DeleteModel(
            name='TeacherTimeTable',
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['teacher', 'day_of_week'], name='attendance__teacher_400510_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school_class', 'day_of_week'], name='attendance__school__ad9235_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('branch', 'school_class', 'teacher', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
