# Generated by Django 5.2.6 on 2026-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_remove_attendance_student_timetable_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['branch', 'day_of_week'], name='attendance__branch__953d34_idx'),
        ),
    ]
