# Generated by Django 5.2.6 on 2026-02-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_timetable_attendance__branch__953d34_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='organization',
        ),
    ]
