# Generated by Django 5.2.6 on 2026-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_remove_teacher_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch'], name='attendance__branch__21716c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='attendance__name_d95c02_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_no'], name='attendance__roll_no_382915_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_name'], name='attendance__class_n_54b5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['branch'], name='attendance__branch__9af288_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='attendance__name_4e6766_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['employee_id'], name='attendance__employe_085743_idx'),
        ),
    ]
