# Generated by Django 5.2.6 on 2026-04-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='room',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='url',
        ),
        migrations.AddField(
            model_name='camera',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='password_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='port',
            field=models.IntegerField(default=554),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_path',
            field=models.CharField(default='/stream1', max_length=200),
        ),
        migrations.AddField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
