# Generated by Django 5.2.6 on 2026-04-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_remove_camera_floor_remove_camera_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
