# Generated by Django 5.2.6 on 2026-04-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_camera_floor_camera_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='password_encrypted',
            field=models.TextField(default='admin123'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='username',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
