services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - minio_data:/data

    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio

    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD &&
      mc mb -p local/attendance-media || true &&
      mc mb -p local/face-db-backups || true &&
      mc anonymous set none local/attendance-media &&
      mc anonymous set none local/face-db-backups
      "

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    restart: "no"

volumes:
  minio_data:
