"""
Django settings for attendance_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
from decouple import config
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
ADMIN_JWT_SECRET = config("ADMIN_JWT_SECRET")

# =================== RUST DLL PATH FIX (Windows) ===================
import os
import sys

# 1. Add Rust wheel location (where .pyd is installed)
VENV_SITE_PACKAGES = BASE_DIR.parent / "venv" / "lib" / "site-packages"
os.add_dll_directory(str(VENV_SITE_PACKAGES))

# ======== MANUAL DLL PATH FIX FOR RUST EXTENSION ========

# Libtorch CPU DLLs
LIBTORCH_PATH = r"C:\tools\libtorch\lib"
if os.path.isdir(LIBTORCH_PATH):
    os.add_dll_directory(LIBTORCH_PATH)
else:
    print("⚠️ Libtorch DLL directory not found")

# OpenCV DLLs
OPENCV_PATH = r"C:\tools\opencv\build\x64\vc16\bin"
if os.path.isdir(OPENCV_PATH):
    os.add_dll_directory(OPENCV_PATH)
else:
    print("⚠️ OpenCV DLL directory not found")

# ONNX Runtime (Rust builds this in target/)
ORT_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "rust_extensions",
    "rust_backend",
    "target",
    "release"
)
if os.path.isdir(ORT_PATH):
    os.add_dll_directory(os.path.abspath(ORT_PATH))
else:
    print("⚠️ ORT DLL dir not found yet (will exist after Rust build)")

# =========================================================

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "corsheaders",
    "django_extensions",
    "storages",
    "attendance",
    "Admin",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Allow frontend (React/Tailwind app) to call APIs
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'attendance_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attendance_backend.wsgi.application'

# Database
DATABASES = {
    "default": dj_database_url.parse(config("DATABASE_URL"), conn_max_age=600)
}

# ================== MINIO STORAGE ==================

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_ACCESS_KEY_ID = config("MINIO_ACCESS_KEY", default="minioadmin")
AWS_SECRET_ACCESS_KEY = config("MINIO_SECRET_KEY", default="minioadmin")

AWS_STORAGE_BUCKET_NAME = config(
    "MINIO_BUCKET_NAME", default="attendance-media"
)

AWS_S3_ENDPOINT_URL = config(
    "MINIO_ENDPOINT", default="http://localhost:9000"
)

AWS_S3_REGION_NAME = "us-east-1"
AWS_S3_ADDRESSING_STYLE = "path"

AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = None

MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"

# ====================== YUNET MODEL PATH (OPTIONAL) ======================

YUNET_MODEL_PATH = BASE_DIR / "rust_extensions" / "rust_backend" / "models" / "face_detection_yunet_2023mar.onnx"

# Convert to string for PyO3
YUNET_MODEL_PATH = str(YUNET_MODEL_PATH) if YUNET_MODEL_PATH.exists() else None

# ===================================================

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static & Media
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ====================== RUST FACE DATABASE ======================
# Path where HNSW + metadata will be saved
FACE_DATABASE_PATH = BASE_DIR / "face_database"
FACE_DATABASE_PATH.mkdir(exist_ok=True)  # Create if not exists

# =============================================================