[build]
rustflags = ["-C", "target-feature=+sse2"]

[target.x86_64-pc-windows-msvc]
linker = "link.exe"

[env]
OPENCV_LINK_LIBS = "opencv_world4110"       # Must match your .lib exactly
OPENCV_LINK_PATHS = "C:\\tools\\opencv\\build\\x64\\vc16\\lib"
OPENCV_INCLUDE_PATHS = "C:\\tools\\opencv\\build\\include"
OPENCV_DISABLE_PROBES = "cmake"
CXXFLAGS = "/std:c++17"
