# Generated by Django 5.2.6 on 2025-12-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('attendance', '0014_delete_adminaccesskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccesskey',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminaccesskey',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_keys', to='attendance.organization'),
            preserve_default=False,
        ),
    ]
